# Generated by Django 3.2.5 on 2023-09-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname', 'firstname']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_name',
        ),
    ]
